### PR TITLE
Update 0058-graceful-pipeline-run-termination.md

### PR DESCRIPTION
**Pull request by wzhanw**
Correct the TEP number， it should be TEP-0046

### CODE REVIEW

**Comment by wzhanw** [comment]
@vdemeester I just signed the CLA,  I had tried it soon after I created the PR, but the EasyCLA has a problem by then, it reported `internal server error` after I clicked the link.

**Review by vdemeester — APPROVED** [review]
@wzhanw thanks. Yeah EasyCLA was flakey few days back... seems like it's back on track
/cc @dibyom @pritidesai @afrittoli

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
