### PR TITLE
[TEP-0105]: Enable graceful canceling of pipelinerun from dashboard 

### PR DESCRIPTION
**Pull request by williamlfish**
This TEP outlines a feature to the dashboard that enables a graceful canceling of a pipelinerun. Please feel free to let me know if there is additional information needed, wanted, or if there is a step in the process I am missing. Thanks!

/kind tep

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
I wonder if this even need a TEP as it's just about support in the dashboard the [graceful termination](https://github.com/tektoncd/community/blob/main/teps/0058-graceful-pipeline-run-termination.md) TEP, but 👍🏼

**Comment by AlanGreene** [comment]
Thanks @williamlfish. I don't think this needs a TEP and we have an issue in the Dashboard repo tracking the same: https://github.com/tektoncd/dashboard/issues/2094

**Comment by williamlfish** [comment]
@vdemeester thank you for looping in @AlanGreene, and to both of you for pointing out the other TEP/Issue, I'm sorry I missed it 😅 . @AlanGreene would you mind if i PR'd the dashboard with this proposed solution, or something similar? 

I'll close this PR none the less and thank y'all again!

**Comment by AlanGreene** [comment]
@williamlfish let's continue the discussion over in the Dashboard issue. You'll see some UX issues I raised originally that we'll need to resolve but I think something like your proposal works for the underlying code 👍  Thanks

**Pull request closed without merging**
