### PR TITLE
TEP-0020: Add s390x architecture support

### PR DESCRIPTION
**Pull request by barthy1**
This TEP proposes the way to add s390x support in Tekton.

The TEP is based on "Add other architectures support" [TEP 19](https://github.com/tektoncd/community/pull/211)
and provides information about specific setup to get access to s390x native hardware.
Sequence diagram with steps to access s390x hardware and run build/e2e tests is also provided.

### CODE REVIEW

**Comment by sbwsg** [comment]
This lgtm too, though I think we need someone from a different org/company to give it the second lgtm and get it merged.

**Review by vdemeester — APPROVED** [review]
/lgtm
/meow

**Pull request merged**
