### PR TITLE
[TEP-0137] Events as implementable

### PR DESCRIPTION
**Pull request by afrittoli**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by khrm** [comment]
I think we need to close and reopen this to solve the CLA issue.

**Comment by lbernick** [comment]
API WG: @afrittoli please rebase/address the TEP linter and after that this looks good to go!

**Comment by afrittoli** [comment]
> API WG: @afrittoli please rebase/address the TEP linter and after that this looks good to go!

Thank you, all updated now

**Pull request merged**
