### PR TITLE
chore: add squakez

### PR DESCRIPTION
**Pull request by squakez**
Will maintain Camel K tasks

Ref #https://github.com/tektoncd/catalog/pull/1166

### CODE REVIEW

**Comment by squakez** [comment]
cc @vinamra28 who has reviewed https://github.com/tektoncd/catalog/pull/1166

Happy to discover how to "officially" support this task in Tekton, as we want to use it as Camel K default "pipeline" technology and take care of its maintenance.

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Review by khrm — COMMENTED** [review]
/approve

**Pull request merged**
