### PR TITLE
Update TEP 109: align type hinting with other type hinting formating …

### PR DESCRIPTION
**Pull request by ywluogg**
Update TEP 109: align type hinting with other type hinting formating to match other type hinting markers in https://github.com/tektoncd/chains/blob/main/docs/intoto.md

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by pritidesai** [comment]
API WG - @afrittoli please take a look, @vdemeester has approved this TEP, thanks!

**Review by dibyom — APPROVED** [review]

**Comment by dibyom** [comment]
LGTMing since its a fairly narrow update to the TEP and reflects the implementation: https://github.com/tektoncd/chains/commit/015ff9a153eb440aabf5ab590fe86a1d0720ee49

**Comment by ywluogg** [comment]
@dibyom lol I didn't know it has be exactly LGTM. Approval seems like not enough lol

**Pull request merged**
