### PR TITLE
Adding startxfr and startx-lab to org

### PR DESCRIPTION
**Pull request by startx-lab**
Catalog Task owner :
OWNER of the ab-load task in the catalog, see https://github.com/tektoncd/catalog/pull/1002.
OWNER of the cerberus-check task in the catalog, see https://github.com/tektoncd/catalog/pull/1004.
OWNER of the kraken-scenario task in the catalog, see https://github.com/tektoncd/catalog/pull/1003.

### CODE REVIEW

**Comment by vdemeester** [comment]
@startx-lab @startxfr can you add a description in the PR / commit on what is the reason for adding yourself to the community (for example like https://github.com/tektoncd/community/pull/680#issue-1201583620 for maintainers of catalog tasks)

**Comment by afrittoli** [comment]
These are the requirements to join the org: https://github.com/tektoncd/community/blob/main/process.md#organization-member

**Comment by vdemeester** [comment]
> These are the requirements to join the org: https://github.com/tektoncd/community/blob/main/process.md#organization-member

@afrittoli isn't the catalog task maintainers overlook in the process ?

**Pull request merged**
