### PR TITLE
TEP-0155 to store PipelineRun/TaskRun Events to DB

### PR DESCRIPTION
**Pull request by khrm**
Tekton Results stores so far PipelineRuns, TaskRuns and Logs. This TEP proposes to store Pipeline Events as well to have all historical data from a PipelineRun in Tekton Results.

Added design to the original PR at https://github.com/tektoncd/community/pull/1118

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind tep

**Review by khrm — COMMENTED** [review]
/assign @sayan-biswas @avinal 
This is recreated from https://github.com/tektoncd/community/pull/1118

Please re-review this.

**Comment by khrm** [comment]
@adambkaplan Sure.

**Comment by khrm** [comment]
I have added the description and PR in the description.
Commit was already showing in GH as `"manuelwallrapp" authored and "khrm" committed`.

**Review by avinal — APPROVED** [review]
Looks good to me, but I would suggest adding proper [DCO](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) in the commit like `Signed-off-by` and `Co-authored-by`.

**Pull request merged**
