### PR TITLE
add arhell to tektoncd members

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/tektoncd/community/issues/773

### CODE REVIEW

**Comment by dibyom** [comment]
hi @Arhell - Could you please update the commit message and PR description with a bit more detail (as you did in the issue?) e.g. something like you'd want to work on the website repo and have already contributed in the past.

**Comment by Arhell** [comment]
> hi @Arhell - Could you please update the commit message and PR description with a bit more detail (as you did in the issue?) e.g. something like you'd want to work on the website repo and have already contributed in the past.

Of course, I mainly want to work on the site to fix bugs, ui , accessibility and much more. Examples of what I did here https://github.com/tektoncd/community/issues/773

**Comment by afrittoli** [comment]
> pull request process

Thank you @Arhell and welcome to the community. 

Before we approve the PR, could you update the git commit message according to our [guidelines](https://github.com/tektoncd/community/blob/main/standards.md#commits) so that we have context in the git log?

**Comment by Arhell** [comment]
> > pull request process
> 
> Thank you @Arhell and welcome to the community.
> 
> Before we approve the PR, could you update the git commit message according to our [guidelines](https://github.com/tektoncd/community/blob/main/standards.md#commits) so that we have context in the git log?

Done

**Comment by afrittoli** [comment]
> Thank you @Arhell and welcome to the community.
> 
> Before we approve the PR, could you update the git commit message according to our [guidelines](https://github.com/tektoncd/community/blob/main/standards.md#commits) so that we have context in the git log?

Thanks for the update; I see no extra info to the commit message, could you write the commit message with a subject and a body as per [guidelines](https://github.com/tektoncd/community/blob/main/standards.md#commits)?
An example of commit message could be:

```
add arhell to tektoncd members

I (arhell) would like to work on the tekton.dev website, fix bugs, improve the user
interface accessibility and more (for example, fixing links at least).

I already contributed several PRs to the website and results repos:
- https://github.com/tektoncd/website/pull/405
- https://github.com/tektoncd/website/pull/393
- https://github.com/tektoncd/website/pull/403
- https://github.com/tektoncd/website/pull/397
- https://github.com/tektoncd/results/pull/212
- https://github.com/tektoncd/results/pull/210
- https://github.com/tektoncd/results/pull/208
```

**Comment by Arhell** [comment]
> > Thank you @Arhell and welcome to the community.
> > Before we approve the PR, could you update the git commit message according to our [guidelines](https://github.com/tektoncd/community/blob/main/standards.md#commits) so that we have context in the git log?
> 
> Thanks for the update; I see no extra info to the commit message, could you write the commit message with a subject and a body as per [guidelines](https://github.com/tektoncd/community/blob/main/standards.md#commits)? An example of commit message could be:
> 
> ```
> add arhell to tektoncd members
> 
> I (arhell) would like to work on the tekton.dev website, fix bugs, improve the user
> interface accessibility and more (for example, fixing links at least).
> 
> I already contributed several PRs to the website and results repos:
> - https://github.com/tektoncd/website/pull/405
> - https://github.com/tektoncd/website/pull/393
> - https://github.com/tektoncd/website/pull/403
> - https://github.com/tektoncd/website/pull/397
> - https://github.com/tektoncd/results/pull/212
> - https://github.com/tektoncd/results/pull/210
> - https://github.com/tektoncd/results/pull/208
> ```

Done.
Thanks!

**Review by afrittoli — COMMENTED** [review]
Thank you for your patience with the commit updates and again welcome!
/approve

**Pull request merged**
