### PR TITLE
Add chitrangpatel to the gov board while dibyom is on leave

### PR DESCRIPTION
**Pull request by dibyom**
As discussed in the May 8 gov board meeting, @chitrangpatel will be taking my place in the Gov Board!

### CODE REVIEW

**Review by jerop — APPROVED** [review]

**Comment by vdemeester** [comment]
cc @afrittoli

**Review by afrittoli — COMMENTED** [review]
Welcome to the GB @chitrangpatel !! 🎉 
/approve

**Comment by jerop** [comment]
All board members have approved/lgtm'ed so removing the hold on this PR

Thank you @dibyom and welcome on board @chitrangpatel 👏🏾  

/unhold

**Pull request merged**
