### PR TITLE
Add Jonas to the org

### PR DESCRIPTION
**Pull request by jlpettersson**
Jonas has recently become a regular contributor. He started with adding a minor [_missing_ `omitempty`](https://github.com/tektoncd/pipeline/pull/2301) and then [proposed some ideas](https://github.com/tektoncd/pipeline/issues/1986#issuecomment-605605058) around workspaces and PersistentVolumeClaim creation and continued to [elaborate around those ideas](https://github.com/tektoncd/pipeline/issues/1986#issuecomment-607436779). A sunny day a few days later, he also submitted an [implementation for volumeClaimTemplate](https://github.com/tektoncd/pipeline/pull/2326), corresponding to the discussed ideas.

A few days later submitted a [small refactoring PR](https://github.com/tektoncd/pipeline/pull/2392), and he also listened to community members that [proposed changes](https://github.com/tektoncd/pipeline/issues/2450) to his implementation about volumeClaimTemplates and did an [implementation for that proposal](https://github.com/tektoncd/pipeline/pull/2453).

A rainy day, he also wrote [technical documentation about PVCs](https://github.com/tektoncd/pipeline/pull/2521) including adding an example that caused _flaky_ integration tests for the whole community during multiple days. When he understood his mistake, he submitted a [removal of the flaky example](https://github.com/tektoncd/pipeline/pull/2546).

He has also put his toe into Tekton Catalog and [contributed to the buildah task](https://github.com/tektoncd/catalog/pull/310).

He has continued to contribute, mostly with more PRs to the Pipeline project:

- https://github.com/tektoncd/pipeline/pull/2460
- https://github.com/tektoncd/pipeline/pull/2491
- https://github.com/tektoncd/pipeline/pull/2502
- https://github.com/tektoncd/pipeline/pull/2506
- https://github.com/tektoncd/pipeline/pull/2632
- https://github.com/tektoncd/pipeline/pull/2633
- https://github.com/tektoncd/pipeline/pull/2634
- https://github.com/tektoncd/pipeline/pull/2636
- https://github.com/tektoncd/pipeline/pull/2601
- https://github.com/tektoncd/pipeline/pull/2630

Jonas is excited about the great community around Tekton and the project! He now would like to join the org.

### CODE REVIEW

**Comment by popcor255** [comment]
/ok-to-test
This looks good to me.
@bobcatfish @sbwsg @skaegi @afrittoli

**Comment by afrittoli** [comment]
/lgtm
Thanks @jlpettersson !!

**Comment by chmouel** [comment]
/lgtm

Thanks jonah and welcome to Tekton

**Comment by bobcatfish** [comment]
Thanks @jlpettersson !!!! :D glad to have you!

cats celebrating

**Pull request merged**
