### PR TITLE
Fix link to add permissions script 🔗

### LINKED ISSUE #358: governance.md link broken
# Expected Behavior

Link to script works

# Actual Behavior

Links to https://github.com/tektoncd/plumbing/blob/main/addpermissions.py which 404s.

### PR DESCRIPTION
**Pull request by bobcatfish**
Was renamed to adjust permissions

Fixes #358

### CODE REVIEW

**Comment by bobcatfish** [comment]
@sbwsg would you like to become a community approver? :D

**Comment by sbwsg** [comment]
> @sbwsg would you like to become a community approver? :D

Created a PR to add me here: #364

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
