### PR TITLE
Mark tep75&76 implemented

### PR DESCRIPTION
**Pull request by chuangw6**
Implementation PRs for TEP 75:
https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+0075+in%3Atitle

Implementation PRs for TEP 76:
https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+0076+in%3Atitle+

### CODE REVIEW

**Comment by chuangw6** [comment]
@ywluogg @Yongxuanzhang Please take a look.

**Comment by lbernick** [comment]
@chuangw6 could you please add the implementation prs directly to the teps?

**Comment by Yongxuanzhang** [comment]
> @chuangw6 could you please add the implementation prs directly to the teps?

75:
https://github.com/tektoncd/pipeline/pull/4786
https://github.com/tektoncd/pipeline/pull/4861
https://github.com/tektoncd/pipeline/pull/4867
https://github.com/tektoncd/pipeline/pull/4878
https://github.com/tektoncd/pipeline/pull/4883
https://github.com/tektoncd/pipeline/pull/4902
https://github.com/tektoncd/pipeline/pull/4904
https://github.com/tektoncd/pipeline/pull/5007
https://github.com/tektoncd/pipeline/pull/5083
https://github.com/tektoncd/pipeline/pull/5088
https://github.com/tektoncd/pipeline/pull/5090
https://github.com/tektoncd/pipeline/pull/5142
https://github.com/tektoncd/pipeline/pull/5144
https://github.com/tektoncd/pipeline/pull/5197
https://github.com/tektoncd/pipeline/pull/5222
76:
https://github.com/tektoncd/pipeline/pull/4779
https://github.com/tektoncd/pipeline/pull/4818
https://github.com/tektoncd/pipeline/pull/4855
https://github.com/tektoncd/pipeline/pull/4908
https://github.com/tektoncd/pipeline/pull/4911
https://github.com/tektoncd/pipeline/pull/4920
https://github.com/tektoncd/pipeline/pull/4965
https://github.com/tektoncd/pipeline/pull/5088
https://github.com/tektoncd/pipeline/pull/5132
https://github.com/tektoncd/pipeline/pull/5139

**Comment by chuangw6** [comment]
> @chuangw6 could you please add the implementation prs directly to the teps?

Sounds good! Added! Thanks @lbernick !

**Comment by chuangw6** [comment]
Thanks @Yongxuanzhang for collecting these links. Added!

**Comment by chuangw6** [comment]
Thank you @ywluogg for leading this project and making it happen (mark implemented!)!

**Pull request merged**
