### PR TITLE
Remove Python 3.8 syntax

### PR DESCRIPTION
**Pull request by bobcatfish**
TIL about the := syntax which Python 3.8 introduced! The docs we have at
the moment say we require 3.6 (and I only have 3.7 installed personally
haha) so this commit removes the 3.8 syntax so that this script will
work with 3.6 (or at least 3.7 from my own attempts so far?).

I think in the long run we can simplify this by assuming folks will run
this via the image so they don't have to install it.

@afrittoli

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by bobcatfish** [comment]
I'm gonna open another PR to fix that lint problem (i wonder how it got into that state?)

**Comment by afrittoli** [comment]
> I'm gonna open another PR to fix that lint problem (i wonder how it got into that state?)

It should be enough to rebase

**Comment by bobcatfish** [comment]
Okay should be rebased!

**Comment by afrittoli** [comment]
I could try to improve this in the CI test by attempting an auto-rebase?
If there is no conflict, it will pass CI, if there is a conflict, it would require rebase in any case.

**Comment by bobcatfish** [comment]
> I could try to improve this in the CI test by attempting an auto-rebase?

I think this kind of thing is part of the reason why Prow (if i'm remembering correctly) tries to merge the PR into master and does tests against the result of that merge, vs just on the PR itself

**Comment by chmouel** [comment]
/lgtm

I wonder why 3.6 is required?

**Pull request merged**
