### PR TITLE
[TEP-0124] Add design and implementation details

### PR DESCRIPTION
**Pull request by kmjayadeep**
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

This PR changes the status of the TEP to `implementable` by adding more design details and completing the missing sections of the proposal.

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by afrittoli** [comment]
FYI @abayer @dibyom since you reviewed the design PR 🙏

**Review by pxp928 — APPROVED** [review]
/approve

**Comment by afrittoli** [comment]
This has three approvals, so it should be ready for an lgtm - we can do it during the API WG today

**Pull request merged**
