### PR TITLE
Mark TEP-0100 as implemented

### PR DESCRIPTION
**Pull request by abayer**
Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

### CODE REVIEW

**Review by lbernick — COMMENTED** [review]
/lgtm

Can you please add a change to pipelines which puts the old status in the deprecations table, and includes the earliest date this flag can have the default value swapped and be removed?

**Comment by lbernick** [comment]
/hold

until that change is made

**Comment by abayer** [comment]
@lbernick Should that wait until there's been a release? And I'm assuming that for now, we want to add the deprecation notice for when the default value will change from `full` to `minimal`, and then when the default's been changed, another notice for when the `full` and `both` options will be removed?

**Comment by lbernick** [comment]
> @lbernick Should that wait until there's been a release? And I'm assuming that for now, we want to add the deprecation notice for when the default value will change from `full` to `minimal`, and then when the default's been changed, another notice for when the `full` and `both` options will be removed?

I would say let's send out an email announcement that this will be available in the next release, update the deprecation table, and then add the link to the release in the deprecation table as soon as it exists? that way we don't forget to update the deprecation table somewhat quickly

**Comment by lbernick** [comment]
> 👍 I've never done an email announcement, so I'm not sure what address to send it to, format, etc - any pointers? =)

No problem! I would just email https://groups.google.com/g/tekton-dev and https://groups.google.com/g/tekton-users explaining how to turn on this feature, the changes we have planned (swapping the feature flag to minimal status in 9 months and then removing) and that this will be available in the next release

**Review by vdemeester — APPROVED** [review]

**Comment by abayer** [comment]
https://github.com/tektoncd/pipeline/pull/4781 has been merged, adding the deprecation notice.

**Comment by abayer** [comment]
hooray! =)

**Pull request merged**
