### PR TITLE
Update Slack invite link

### LINKED ISSUE #1066: Slack invite link doesn’t work
The slack invite link in the docs doesn’t work, slack is telling me it’s been revoked.

### PR DESCRIPTION
**Pull request by dibyom**
The old link expired.
Fixes #1066

### CODE REVIEW

**Review by jerop — APPROVED** [review]
/lgtm

**Review by khrm — COMMENTED** [review]
/approve

**Comment by dibyom** [comment]
cc @afrittoli @wlynch could one of you approve this?

**Comment by JeromeJu** [comment]
Looks like the link has been outdated again? :/ cc @tektoncd/community-maintainers

**Pull request merged**
