### PR TITLE
Add Lee Bernick to community collaborators

### PR DESCRIPTION
**Pull request by lbernick**
Based on the [requirements](https://github.com/tektoncd/community/blob/main/process.md#reviewer)
in our contributor ladder, I am eligible to be a "reviewer" in the community repo based on my
nomination from an OWNER of another Tekton project.

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
/meow

**Review by pritidesai — APPROVED** [review]

**Pull request merged**
