### PR TITLE
TEP-0069: Update the test plan.

### PR DESCRIPTION
**Pull request by ScrapCodes**
Previously, the proposal had lot of changes to tekton controller.
 After updating the proposal to "let the custom controller do the hard work",
 the new approach does not require the same test plan as before.

### CODE REVIEW

**Comment by pritidesai** [comment]
/assign @jerop 
/assign @afrittoli 

we can merge this ouside of the API WG cycle

**Review by afrittoli — COMMENTED** [review]
Thanks for the update.
/approve

**Review by jerop — APPROVED** [review]
thanks @ScrapCodes

**Pull request merged**
