### PR TITLE
[TEP-0090]: Renaming docker use case to "Monorepo".

### PR DESCRIPTION
**Pull request by Oded-B**
I think the more generic term applies, will make the case for this TEP stronger and will help more people find it.

### CODE REVIEW

**Review by jerop — APPROVED** [review]
Thank you @Oded-B! 🎉 

I have two requests: 
1. update the title of the use case to reflect the expanded scope
2. add https://github.com/tektoncd/pipeline/issues/1922 to the issues section in the reference section of the TEP

**Comment by jerop** [comment]
thanks for the prompt updates @Oded-B 

please squash the commits to one commit per our standards - https://github.com/tektoncd/community/blob/main/standards.md#commits

**Review by jerop — COMMENTED** [review]
thanks for the updates @Oded-B :thanks

need other tekton pipelines owners to approve (at least one more) - cc @tektoncd/core-maintainers

**Review by vdemeester — APPROVED** [review]

**Comment by jerop** [comment]
API WG on 01/10

/lgtm

**Pull request merged**
