### PR TITLE
Add eddie4941 as a new member

### PR DESCRIPTION
**Pull request by eddie4941**

### CODE REVIEW

**Comment by bobcatfish** [comment]
Hey there @eddie4941 ! It looks like you'll need to sign the CLA before continuing.

Also can you explain a bit more about your interest in the project?

Thanks!

**Comment by bobcatfish** [comment]
@eddie4941 is working on https://github.com/tektoncd/pipeline/issues/1273

**Comment by chmouel** [comment]
/lgtm

@eddie4941 you will need have to do the CLA  signing please.

**Comment by eddie4941** [comment]
Closing this for now while we sign CLA.

**Pull request closed without merging**
