### PR TITLE
Add myself as a Chains collaborator

### PR DESCRIPTION
**Pull request by mattmoor**
I've been in OWNERS for 6 months: https://github.com/tektoncd/chains/commit/a17c83748773c7aa06e2ee9db242c0cf5c856507

cc @priyawadhwa @dlorenc

### CODE REVIEW

**Review by priyawadhwa — APPROVED** [review]
🥳

**Review by dibyom — APPROVED** [review]

**Comment by dlorenc** [comment]
/lgtm

this appears stuck

**Pull request merged**
