### PR TITLE
Add openrefactory to org

### PR DESCRIPTION
**Pull request by openrefactory**
Please add `openrefactory` as a member to the org. I will be maintaining the icr-scan task from this PR (https://github.com/tektoncd/catalog/pull/1160)

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
Please sign cla.

**Comment by vinamra28** [comment]
@openrefactory are you still looking at this PR?

**Comment by vdemeester** [comment]
ping @openrefactory

**Comment by vdemeester** [comment]
As there have been no activities for a long time, I'll go ahead and close this one. @openrefactory please comment on this pull-request if you want us to re-open it.

**Pull request closed without merging**
