### PR TITLE
Add jinchihe as memeber

### PR DESCRIPTION
**Pull request by jinchihe**
I'm working to generate OpenAPI and swagger file for Tekton pipeline(https://github.com/tektoncd/pipeline/pull/3081), and then generate SDK for pipeline (https://github.com/tektoncd/experimental/pull/622).  The effort and changes are huge.

Now I need to join tekton and maintain the Python SDK for tekton. Thanks a lot!

### CODE REVIEW

**Comment by jinchihe** [comment]
/cc @afrittoli   
Seems block the Python SDK generation PR merging. :-) Would you please approve? Great thanks.

**Comment by afrittoli** [comment]
Thank you @jinchihe for your contributions!

@vdemeester @bobcatfish @ImJasonH @abayer I support @jinchihe joining the Tekton org
/approve

**Pull request merged**
