### PR TITLE
TEP-0021 Results API: Mark TEP as implementable.

### PR DESCRIPTION
**Pull request by wlynch**
/kind tep

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
I'm definitely lgtm on this.
Since this is a new project, I wonder if @bobcatfish @ImJasonH @vdemeester would like to give a ack on moving forward.
/hold
/approve

**Comment by ImJasonH** [comment]
/lgtm

🎉

**Comment by wlynch** [comment]
Thanks everyone! :D 

/hold cancel

**Pull request merged**
