### PR TITLE
Mark TEP-0121 As Implemented

### PR DESCRIPTION
**Pull request by XinruZhang**
TEP-0121 is implemented by:
- https://github.com/tektoncd/pipeline/pull/5842
- https://github.com/tektoncd/pipeline/pull/5853
- https://github.com/tektoncd/pipeline/pull/5844

### CODE REVIEW

**Comment by XinruZhang** [comment]
@tektoncd/community-collaborators PTAL ❤️

**Review by afrittoli — COMMENTED** [review]
Thank you!
/approve

**Review by jerop — APPROVED** [review]
Please add the implementation PRs in the references section: 

https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+TEP-0121+

Example: https://github.com/tektoncd/community/blob/main/teps/0127-larger-results-via-sidecar-logs.md#references

**Review by jerop — COMMENTED** [review]
/lgtm

Congratulations @XinruZhang!

**Pull request merged**
