### PR TITLE
org: remove duplicated names from cli.collaborators

### PR DESCRIPTION
**Pull request by vdemeester**
In order to fix the following error

```
{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure tektoncd teams: failed to update cli.collaborators members: users in both roles: chmouel, vdemeester","severity":"fatal","time":"2021-07-23T07:39:37Z"}
```

We should see if peribolos has a dry-run/validate command 👼🏼 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
Actually it does 😛 We should run a test if `org.yaml` has changed without `--confirm=true` (maybe we might not even need the token but I doubt it)

```
/peribolos -config-path /workspace/repo/$(params.configPath) -fix-org
    -fix-org-members -fix-teams -fix-team-repos -fix-team-members
    -github-token-path /etc/github/bot-token
```

**Comment by afrittoli** [comment]
/lgtm

Yes, indeed, we need a CI job for that :)

**Comment by vdemeester** [comment]
> /lgtm
> 
> Yes, indeed, we need a CI job for that :)

Working on that 😝

**Review by afrittoli — COMMENTED** [review]
/approve

**Pull request merged**
