### PR TITLE
Add mooyeg to the org

### PR DESCRIPTION
**Pull request by MoOyeg**
Added myself to the org, based on the suggestion in this PR: tektoncd/catalog#788

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by vdemeester** [comment]
@afrittoli interestingly, I think the job to validate the `org` file in not there anymore, not sure why ? 🤔

**Comment by afrittoli** [comment]
> @afrittoli interestingly, I think the job to validate the `org` file in not there anymore, not sure why ? 🤔

It is there, but since it's not marked as required (in terms of branch protection), it doesn't show up in the list until the job starts running on Tekton side.

**Comment by vdemeester** [comment]
> > @afrittoli interestingly, I think the job to validate the `org` file in not there anymore, not sure why ? thinking
> 
> It is there, but since it's not marked as required (in terms of branch protection), it doesn't show up in the list until the job starts running on Tekton side.

ohh but then it didn't start for this one 🤔

**Comment by afrittoli** [comment]
> > > @afrittoli interestingly, I think the job to validate the `org` file in not there anymore, not sure why ? thinking
> > 
> > 
> > It is there, but since it's not marked as required (in terms of branch protection), it doesn't show up in the list until the job starts running on Tekton side.
> 
> ohh but then it didn't start for this one 🤔

image

Isn't `pull-community-org-validation` the one you're talking about? I see it there :)

**Pull request merged**
