### PR TITLE
Updated Documentation working group

### PR DESCRIPTION
**Pull request by anneqm**
Two changes: 
1. updated time .. we meet at 11am now, no longer at 1pm Eastern. 
2. Added Alan as additional facilitator. 

Probably should also remove Kim as facilitator and fix Serge's github ID.. did not make those updates.

### CODE REVIEW

**Comment by popcor255** [comment]
I think you need to do the cla first.

**Comment by anneqm** [comment]
Yes, I am working thru the process to be added to the new CLA under IBM.. hopefully will have that in place by tomorrow.

**Comment by anneqm** [comment]
@popcor255 Corportate CLA now in place. Thank you!

**Pull request merged**
