### PR TITLE
TEP-0023: Implicit Params - mark as implementable.

### PR DESCRIPTION
**Pull request by wlynch**
There were no outstanding comments in
https://github.com/tektoncd/community/pull/444, so going ahead with
marking this as implementable as-is.

### CODE REVIEW

**Comment by bobcatfish** [comment]
Assigning the folks that were assigned to #444:

/assign @bobcatfish
/assign @vdemeester
/assign @nikhil-thomas

Also sounds good to me!
/approve

**Review by vdemeester — APPROVED** [review]

**Comment by bobcatfish** [comment]
@wlynch I think we could update this now to be "implemented"?

**Pull request merged**
