### PR TITLE
changing the status to implementable

### PR DESCRIPTION
**Pull request by pritidesai**
Changing the status to implementable along with the workflow

### CODE REVIEW

**Comment by bobcatfish** [comment]
I'm happy with this, but I'm also part of proposing it! What do other folks think @vdemeester @afrittoli @sbwsg @ImJasonH @dibyom @dlorenc ?

**Comment by dlorenc** [comment]
Looks good to me!

**Comment by ImJasonH** [comment]
/lgtm

🎉

**Comment by vdemeester** [comment]
@pritidesai you might need to amend/force-push to trigger the EasyCLA check again :sweat:

**Pull request merged**
