### PR TITLE
Add matrix beta to roadmap

### PR DESCRIPTION
**Pull request by afrittoli**
The beta of the matrix feature (tracked in https://github.com/tektoncd/pipeline/issues/5265) should be part of our 2023 roadmap.

### CODE REVIEW

**Review by jerop — COMMENTED** [review]
+1 for adding matrix beta to the roadmap

did you intend to include the TEP-0128 changes in this PR?

**Comment by afrittoli** [comment]
> +1 for adding matrix beta to the roadmap
> 
> did you intend to include the TEP-0128 changes in this PR?

Thanks @jerop - fixed that now

**Review by jerop — APPROVED** [review]
/lgtm

**Comment by pritidesai** [comment]
Hey @afrittoli this sound a little weird since you are the author:

**To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from afrittoli after the PR has been reviewed.**

I will try closing and re-opening this!

**Pull request merged**
