### PR TITLE
Change status of TEP0073 to implemented

### PR DESCRIPTION
**Pull request by khrm**
This TEP was implemented by the pr https://github.com/tektoncd/pipeline/pull/4201

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by afrittoli — COMMENTED** [review]
Thanks @khrm - could you update the TEP table so it will pass CI?

**Comment by pritidesai** [comment]
thank you @khrm for all the great work on this! 🎉  Appreciate it 🙏  

The `config-observability` is set to these values by default:

https://github.com/tektoncd/pipeline/blob/9c529d3b045136d652557a919490c3a2dcf891ca/config/config-observability.yaml#L56-L61

Are we expected to change these defaults as documented here?

> Levels for taskrun and pipelinerun will be changed to task and pipeline respectively in the next release.

https://github.com/tektoncd/pipeline/blob/main/docs/metrics.md#configuring-metrics-using-config-observability-configmap

**Comment by khrm** [comment]
@pritidesai I raised a pr to change default values. Added that pr in the list.

**Comment by pritidesai** [comment]
https://github.com/tektoncd/pipeline/pull/4630 is merged now, the API compatibility policy for metrics being tracked in https://github.com/tektoncd/pipeline/issues/4544

@khrm please rebase this PR

/approve

**Review by jerop — APPROVED** [review]
thanks @khrm!

**Comment by khrm** [comment]
@pritidesai I rebased the pr.

**Comment by pritidesai** [comment]
API WG - merging

/lgtm

**Pull request merged**
