### PR TITLE
TEP-0051 : Add ppc64le architecture support

### PR DESCRIPTION
**Pull request by bahetiamit**
This TEP proposes to add ppc64le architecture support extending [TEP 19](https://github.com/tektoncd/community/pull/211) - which proposes to add other architectures support.

It provides information about setup and access to ppc64le native hardware & outlines the integration to build and run e2e tests on ppc64le hardware.

### CODE REVIEW

**Comment by bahetiamit** [comment]
@vdemeester I am not clear on what needs to be done for pull-community-teps-lint job failure. Any pointers?

**Comment by pritidesai** [comment]
assigning it to @vdemeester @afrittoli @sbwsg

**Comment by sbwsg** [comment]
Given this is based on TEP-0019 and the risks, goals and mitigations remain largely the same I don't see anything that prevents this any more than prevents other architectures.  What do others think?

/lgtm

**Comment by bahetiamit** [comment]
Updated the TEP # to 51 to avoid conflict with merged PR.

**Comment by ghatwala** [comment]
hey @vdemeester  - is there anything else needed for this to be merged ?

**Comment by bobcatfish** [comment]
Both @sbwsg and @vdemeester are out this week, but both approved and there were no objections. @afrittoli and @danielhelfand you are both also assigned - any objections to merging this?

**Pull request merged**
