### PR TITLE
Adding Approval Tasks for Tekton based on Automatiko

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
This is really cool 😎  thank you @mswiderski for sharing!
BTW, we're working on the custom tasks beta - so keep an eye on these:

- https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md
- https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+is%3Aopen+0114

and let us know if there are things you'd like to see in the beta that are not planned yet

/approve

**Comment by mswiderski** [comment]
thanks a lot @afrittoli , will certainly look into it and plan for upgrade in approval task

**Review by vdemeester — APPROVED** [review]

**Comment by mswiderski** [comment]
is there anything else I should do with this PR? Just synced it with main branch

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by afrittoli** [comment]
@mswiderski it looks like you ended up having a merge commit in your PR.
Could you rebase the original commit on `main` instead so that the PR only contains one commit?
Thank you!!

**Comment by mswiderski** [comment]
@afrittoli done, should be small and clean now

**Comment by afrittoli** [comment]
Thanks!
/approve
/lgtm

**Pull request merged**
