### PR TITLE
[TEP Process] Add "Collaborators" option

### PR DESCRIPTION
**Pull request by lbernick**
This commit adds the ability to specify "collaborators" for a TEP.
The intention of this commit is to recognize the efforts of contributors
who take the time to review and understand a proposed design, or contributors
who may have worked on part of the design but are not owners of the
entire design.

### CODE REVIEW

**Comment by lbernick** [comment]
> do we want to add a "reviewers" option too?

Good question! I view a collaborator as a bit different from a reviewer, so it could make sense to have them as separate categories, although there's a lot of potential for overlap. I'm tempted to say let's stick with just collaborator for now, but I don't have a strong opinion here.

**Review by dibyom — APPROVED** [review]

**Comment by jerop** [comment]
@afrittoli @priyawadhwa please take a look

**Review by priyawadhwa — APPROVED** [review]

**Comment by afrittoli** [comment]
Thanks @lbernick 
/lgtm

**Review by afrittoli — COMMENTED** [review]
/approve

**Comment by afrittoli** [comment]
Removing the hold since all GB members approved

**Pull request merged**
