### PR TITLE
Move optional workspaces TEP to implementable

### PR DESCRIPTION
**Pull request by sbwsg**
The optional workspaces TEP was pretty thoroughly edited and reviewed
during the proposal phase (https://github.com/tektoncd/community/pull/169).
There were no outstanding blockers or requests for more information that
I'm aware of that should prevent this TEP moving to implementable.

This PR moves the optional workspaces TEP into implementable state with
intention to go ahead and add this feature to Tekton Pipelines.

### CODE REVIEW

**Comment by bobcatfish** [comment]
I'm happy to go ahead! Wouldn't mind hearing from a couple more @tektoncd/core-maintainers folks before we merge if possible

/lgtm

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Comment by sbwsg** [comment]
Per [our TEP instructions](https://github.com/tektoncd/community/tree/master/teps#merging-teps) we have approvals from owners from at least two companies.  seems ready to merge?  would someone mind giving the approve flag?

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
