### PR TITLE
add skelterjohn to org members

### PR DESCRIPTION
**Pull request by skelterjohn**

### CODE REVIEW

**Comment by bobcatfish** [comment]
Hey there @skelterjohn ! Looks like you need to sign the CLA / follow the link to verify your association with Google.

We have [these requirements for joining the org](https://github.com/tektoncd/community/blob/master/org/README.md#requirements) - could you explain a bit more about why you need to join the org? Note that for many folks they can contribute effectively without needing to join the org

/hold

**Comment by skelterjohn** [comment]
This jasmuth at google, @dlorenc asked me to join the org so I could help out as an owner for tekton chains.

**Pull request merged**
