### PR TITLE
Update the productivity working group meetings

### PR DESCRIPTION
**Pull request by afrittoli**
We have alternate times, so update the meeting details accordingly.
Normalise a bit the markdown tables for all meetings to keep them
more managable.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

### CODE REVIEW

**Comment by afrittoli** [comment]
@vdemeester @bobcatfish could you check if the time in ET is correct? My understanding is that those meeting times follow the US daylight savings calendar, since the time of the meeting changed for two weeks in the UK until daylight savings starts here too.

To produce the link to the calendar entry, I used `(...) -> Publish -> Copy link` which produces a link with a `tmsrc` parameter set to my email. Other WG have links with the `tmsrc` set to either `google.com_d3ovcvo1p3219h989573v98fns%40group.calendar.google.com` or @bobcatfish 's email. I think one needs to be an admin of the shared calendar to get a link without a personal email in it. 
I don't mind really, but if either of you can produce a group link I'd be happy to replace it in the PR.

**Review by sbwsg — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]

**Comment by bobcatfish** [comment]
thanks for updating this @afrittoli !

/lgtm

**Comment by sbwsg** [comment]
/lgtm

Thanks @afrittoli !

**Pull request merged**
