### PR TITLE
Update TEP-0106 Status as Implementable

### PR DESCRIPTION
**Pull request by austinzhao-go**
/kind misc
Update status as "implementable" as the implementation is under review now.

Implementation PR: [here](https://github.com/tektoncd/pipeline/pull/4834)

### CODE REVIEW

**Comment by austinzhao-go** [comment]
Hi @jerop @ncskier could I have a lgtm for this brief tep status update PR?

**Review by jerop — APPROVED** [review]

**Comment by lbernick** [comment]
I'm not sure if we need a non google approver/ the normal rules since https://github.com/tektoncd/community/pull/695 is the PR that actually introduced the full proposal? I think #695 probably should have marked this as implementable and since there's no new content being introduced here, I'm going to LGTM to unblock Austin, but if anyone has any concerns please let me know.

/lgtm

**Pull request merged**
