### PR TITLE
TEP-0075: Add design proposal to handle edge cases

### PR DESCRIPTION
**Pull request by chuangw6**
- Collision when other parameter names contain dots .
- Problem when the object parameter name itself or its key name
contains dots .

### CODE REVIEW

**Comment by lbernick** [comment]
@chuangw6 thanks for these updates! would you mind discussing how this impacts results as well as params? I remember you mentioned we don't support dots for results (but not completely sure if that is right).

@mattmoor this is probably also relevant to you since you wrote the TEP introducing dots in params

**Comment by ywluogg** [comment]
Link this to #4723

**Comment by ywluogg** [comment]
> /cc @chuangw6 @ywluogg @lbernick @jerop what are we planning to do with this PR?

This is for adding some clarifications when param / object names are having . dots involved. I still haven't finished my review of this yet...

**Comment by dibyom** [comment]
API WG: Waiting on reviews

**Comment by chuangw6** [comment]
Hi @ywluogg ,
Please take a look. Let me know if you have any comments.
Thanks.

**Comment by chuangw6** [comment]
Hi @jerop ,
Please take a look. Thanks.

**Review by lbernick — APPROVED** [review]

**Review by ywluogg — APPROVED** [review]

**Comment by jerop** [comment]
API WG 08/22

need a non-googler approver, please take a look @wlynch

**Review by vdemeester — APPROVED** [review]

**Comment by pritidesai** [comment]
API WG - ready to merge

/lgtm

**Pull request merged**
