### PR TITLE
Add chuangw6 to chains collaborators.

### PR DESCRIPTION
**Pull request by wlynch**

### CODE REVIEW

**Review by priyawadhwa — APPROVED** [review]
congrats @chuangw6 !!

**Comment by chuangw6** [comment]
Hey @wlynch @priyawadhwa, 
Thank you for adding me as collaborator! It's a pleasure working with you all! Looking forward to working together on more fun stuff in Chains!

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
