### PR TITLE
TEP-0007: Conditions Beta - further discussion and status update

### PR DESCRIPTION
**Pull request by jerop**
Added [Conditions Beta TEP](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md) in https://github.com/tektoncd/community/pull/159

Let's discuss the TEP further and explore making it implementable per the TEP workflow

cc pipeline owners: @vdemeester @afrittoli @pritidesai @bobcatfish @sbwsg @ImJasonH @dibyom @dlorenc

### CODE REVIEW

**Comment by vdemeester** [comment]
> Added [Conditions Beta TEP](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md) in #159
> 
> Let's discuss the TEP further and explore making it implementable per the TEP workflow
> 
> cc pipeline owners: @vdemeester @afrittoli @pritidesai @bobcatfish @sbwsg @ImJasonH @dibyom @dlorenc

you can do @tektoncd/core-maintainers too :stuck_out_tongue:

**Comment by bobcatfish** [comment]
I am 👍  for this but also I was part of this design so I'm very biased :D

Could some other OWNERs weigh in on whether they think we are ready to make this implementable, @vdemeester @pritidesai ( @tektoncd/core-maintainers :D )

**Comment by sbwsg** [comment]
:+1: from me too!

**Comment by pritidesai** [comment]
👍 from me three 😊

**Comment by dibyom** [comment]
Let's ship it!
/lgtm

**Pull request merged**
