### PR TITLE
Add Avinal to Results Collaborator/Maintainer

### PR DESCRIPTION
**Pull request by khrm**
Avinal has been reviewing and raising PRs for results. Let's add him to the results collaborator and 
maintainer.

@dibyom @vdemeester @alan-ghelardi @adambkaplan @sayan-biswas

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Comment by adambkaplan** [comment]
/lgtm

Evidence:

- [DevStats](https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=tektoncd%2Fresults&var-country_name=All) score of over 100.
- Meaningful [code contributions ](https://github.com/tektoncd/results/pulls?q=is%3Apr+author%3Aavinal+is%3Amerged).
- Active participation in [code reviews](https://github.com/tektoncd/results/pulls?q=is%3Apr+reviewed-by%3Aavinal+)
- Active participation and leadership in [working group meetings](https://docs.google.com/document/d/1GXKq-tc4oJUHdjIe-usHclugVU06sljo4i8BT2OaHbY/edit#heading=h.u0v7zvvs9jkp).

**Pull request merged**
