### PR TITLE
Mark TEP-0016 and TEP-0024 as implemented.

### PR DESCRIPTION
**Pull request by dibyom**
Both concise TriggerBindings and embedded TriggerTemplates have been
implemented.

### CODE REVIEW

**Comment by bobcatfish** [comment]
@dibyom for history could you include a link to the PRs?

/approve

**Comment by bobcatfish** [comment]
> could you include a link to the PRs?

i mean just in comments on this PR but now i wonder if it would make sense to include in the markdown as well - anyway either way for now :D

**Comment by dibyom** [comment]
Embedded TriggerTemplates were added in https://github.com/tektoncd/triggers/pull/783 and Bindings in https://github.com/tektoncd/triggers/pull/768

The TEPs contain links to the GitHub issues that reference those PRs!

**Review by afrittoli — COMMENTED** [review]
\o/

Thanks!
/lgtm

**Pull request merged**
