### PR TITLE
TEP-0033: Mark as implemented

### PR DESCRIPTION
**Pull request by abayer**
https://github.com/tektoncd/pipeline/pull/3881 is the "main" PR for this

cc @afrittoli

### CODE REVIEW

**Review by dibyom — COMMENTED** [review]
@sbwsg Should this be implementing or implemented?

**Comment by sbwsg** [comment]
Yeah I'd consider that TEP in its "done" state now - thanks for updating it @abayer! - new flags will continue to be introduced for behaviour deprecations but I think all the machinery is in place. We will at some point need to add `enable-api-fields: "stable"` but I don't think the specific flag values are blockers to calling the TEP done. `implemented` sgtm!

**Comment by abayer** [comment]
@sbwsg Updated!

**Review by jerop — APPROVED** [review]
thanks @abayer

**Pull request merged**
