### PR TITLE
Add myself and @n3wscott

### PR DESCRIPTION
**Pull request by mattmoor**
/assign @dlorenc @bobcatfish @ImJasonH

### CODE REVIEW

**Comment by bobcatfish** [comment]
Hey @ImJasonH @mattmoor @n3wscott can we update this with some details about who you fine folks are and why you need to be added to the org? Many people probably already know you but we've recently introduced some requirements for joining the org that we'd like to comply with: https://github.com/tektoncd/community/blob/master/org/README.md#requirements

**Comment by mattmoor** [comment]
Sure, I'll elide the parts of our rap sheet that aren't relevant to Tekton 😇 

@n3wscott and I are maintainers on a variety of projects peripheral to Tekton that it depends on in various ways (and some of which it was once a part of!).  In particular, we are some of the core maintainers of the libraries and tools in `knative.dev/pkg` and try to keep Tekton from drifting too far behind.

In addition, Scotty is one of the main folks working on the Go cloudevents SDK (which Tekton consumes), and has been dipping his toe in the `tektoncd/triggers` space, which relates to his day job as one of the leads of the Knative eventing sources working group.

I started and help maintain `google/go-containerregistry` and `google/ko` (which Tekton uses).  I am one of the founders of Knative, sit on its Technical Oversight Committee, and started/led `knative/build` (from which `tektoncd/pipeline` derives).

@bobcatfish does that work? 😅

**Comment by bobcatfish** [comment]
That's great, thanks @mattmoor for the extra context! And my apologies for being so pedantic 😅

**Pull request merged**
