### PR TITLE
Add crshnburn to Org

### PR DESCRIPTION
**Pull request by crshnburn**
PR #920 in the tektonccd/catalog repo has been raised to add a Gradle task which I am offering to be the OWNER for. This PR is to add myself to the Org to allow this to happen as requested in the review comments on that PR.

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by afrittoli** [comment]
Thanks @crshnburn, sounds good to me. Let's wait for a non-IBM/RedHat approval on this :)

**Review by dibyom — APPROVED** [review]

**Pull request merged**
