### PR TITLE
Add xinruzhang to org

### PR DESCRIPTION
**Pull request by ImJasonH**
cc @xinruzhang 👋

### CODE REVIEW

**Comment by XinruZhang** [comment]
@ImJasonH  Thanks Jason :)

**Review by sbwsg — APPROVED** [review]

**Comment by XinruZhang** [comment]
/assign @imjasonh
It seems like it also requires your approval  🙂

**Comment by bobcatfish** [comment]
Welcome @XinruZhang !

/approve

**Comment by bobcatfish** [comment]
oh wait

/hold

**Comment by bobcatfish** [comment]
Before we merge we should provide some context on why we are adding this person to the org (https://github.com/tektoncd/community/blob/master/org/README.md#requirements)

@XinruZhang has joined the team at google and will be working on Tekton! 🎉 

Okay there we go :D

/hold cancel

**Comment by ImJasonH** [comment]
Can I self-approve? Let's find out 😄 

/approve

**Pull request merged**
