### PR TITLE
Add a table of TEPs to the README

### PR DESCRIPTION
**Pull request by afrittoli**
The table is generated using a mustache template and a python script.
The python script for now only reads TEPs in the repo.
Future versions will include numbers from PRs.

The script performs light validation on the TEP documents.
In future we can use this to enforce that a TEP is well formatted and
with a valid number as part of CI. Example log:

```
WARNING:root:TEP number TEP-0012 from filename does not match TEP number TEP-0008 from title (# TEP-NNNN) in 0012-api-spec.md
WARNING:root:No TEP number title (# TEP-NNNN) in 0006-tekton-metrics.md
WARNING:root:No TEP number title (# TEP-NNNN) in 0001-tekton-enhancement-proposal-process.md
```

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

### CODE REVIEW

**Comment by bobcatfish** [comment]
I haven't looked at the python code in detail but in general this is great!! Thanks @afrittoli !

/approve

**Comment by vdemeester** [comment]
/lgtm
@afrittoli needs a rebase :wink:

**Pull request merged**
