### PR TITLE
update Tekton results WG meeting

### LINKED ISSUE #1057: make Tekton Results WG meeting for Europe + Asia  weekly
## Background

Since US + EU meeting was closed due to low attendance. We are currently having a biweekly meeting. 

## Current
Recently, there has been a bump in the number of regular attendees as well as topics to discuss due to increased activity in Tekton Results. The development is taking pace and a biweekly 30-min call is not able to meet the need.

## Proposal

As discussed in the WG call of Aug 17th, we [agreed](https://docs.google.com/document/d/1GXKq-tc4oJUHdjIe-usHclugVU06sljo4i8BT2OaHbY/edit#heading=h.t712v4wlun20) on making the Europe + Asia call weekly.

### PR DESCRIPTION
**Pull request by avinal**
update the Tekton Results Europe + Asia WG meeting to weekly on the same time
fixes #1057

### CODE REVIEW

**Review by enarha — COMMENTED** [review]
/lgtm

**Review by khrm — COMMENTED** [review]
/approve

**Comment by khrm** [comment]
Please fix the spelling mistake in the title.

**Review by khrm — COMMENTED** [review]
Also fix the subject in the commit.

**Review by wlynch — APPROVED** [review]
/lgtm

**Pull request merged**
