### PR TITLE
Add lbernick to Pipeline collaborators

### PR DESCRIPTION
**Pull request by lbernick**
I have been contributing to tektoncd/pipeline for about 3 months, with 12 merged and 14 total PRs,
17 review comments and 62 issue comments, as evidenced by the devstats dashboard.

### CODE REVIEW

**Comment by bobcatfish** [comment]
Happy to be your nominator!

> as evidenced by the devstats dashboard.

@lbernick could you include some links showing the stats you mentioned as well?

For the links:
/hold

From me:
/approve

**Comment by lbernick** [comment]
Added dashboard link to the commit message.

- [contributions](https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=tektoncd%2Fpipeline&var-country_name=All)
- [merged PRs](https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=merged_prs&var-repogroup_name=tektoncd%2Fpipeline&var-country_name=All)
- [comments](https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=comments&var-repogroup_name=tektoncd%2Fpipeline&var-country_name=All)

My [first PR](https://github.com/tektoncd/pipeline/pull/4336) to Pipelines was merged on 10/28/21, about three months ago.

**Review by dibyom — APPROVED** [review]

**Comment by afrittoli** [comment]
Happy to have you on the team, thank you for all your great contributions!
/approve

**Review by vdemeester — APPROVED** [review]

**Comment by bobcatfish** [comment]
I think process wise we are good to go! Thanks @lbernick !

/hold cancel
/lgtm

**Pull request merged**
