### PR TITLE
TEP to store PipelineRun/TaskRun Events to Tekton Results DB

### PR DESCRIPTION
**Pull request by manuelwallrapp**
Tekton Results stores so far PipelineRuns, TaskRuns and Logs. This TEP proposes to store Pipeline Events as well to have all historical data from a PipelineRun in Tekton Results.

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

I concur that storing event history of a `PipelineRun`/`TaskRun` makes sense. The underlying data model is flexible enough that we can store it, though I can foresee challenges tying events to a `TaskRun` when the relevant `Result` object is for a parent `PipelineRun`. This should be addressed when updating the proposal to "implementable", in addition to the following:

1. Logic for filtering/reconciling Events
2. Any new api endpoints that should be added
3. Drawbacks with respect to experience, performance
4. Potential alternatives - are there other solutions which address this problem?

**Review by dibyom — APPROVED** [review]

**Comment by chitrangpatel** [comment]
API WG: Please fix lint issue. This is good to go after.

**Comment by khrm** [comment]
Merged here: #1148

**Comment by khrm** [comment]
Why is "/close" comment not working, @afrittoli @dibyom ?

**Comment by chitrangpatel** [comment]
Designed in https://github.com/tektoncd/community/pull/1148 instead. Closing this.

**Pull request closed without merging**
