### PR TITLE
Request for renzodavid9 to be member of Tekton

### PR DESCRIPTION
**Pull request by renzodavid9**
Request to add renzodavid9 (me 😸 ) to Tekton members. I'm part of Google Tekton team. Thanks!

### CODE REVIEW

**Comment by chitrangpatel** [comment]
Thanks @renzodavid9 for all your contributions!!
/approve

**Comment by wlynch** [comment]
[Ladder Requirements](https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md#organization-member):

- [x] Authored or Reviewed 5 PRs: https://github.com/search?q=org%3Atektoncd+author%3Arenzodavid9+is%3Amerged&type=pullrequests
- [x] Endorsed by existing Org Member: @chitrangpatel 

/approve

**Comment by lcarva** [comment]
Late to the party, but +1 from me! :grin:

**Pull request merged**
