### PR TITLE
Add JeromeJu to Reviewers

### PR DESCRIPTION
**Pull request by JeromeJu**
Self nominating to become a pipeline reviewer:)
I have been contributing to pipelines regularly working on the the pipeline v1 release including the CRD release, pipelineResource migration, pipelineRunStatus migration and features like csi volume workspace support as well. 
And I have met all the requirements for being a project reviewer including the review requirements: https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+reviewed-by%3AJeromeJu+-author%3AJeromeju

/assign @tektoncd/core-maintainers

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Review by jerop — APPROVED** [review]
Thank you for all your contributions @JeromeJu 🎉 

/meow

**Comment by afrittoli** [comment]
> > Thanks, @JeromeJu for your self-nomination.
> > According to our [contributor-ladder](https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md#reviewer) the nomination PR should be open against the repository for which the individual is nominated as a reviewer. This is so that maintainers of that repo may approve the PR should they decide to. Usually, nominations are discussed beforehand by the project maintainer team, so that the approval on the PRs and which repo they go in first is just a formality.
> > It would be really helpful if you could provide the link to 5 PRs for which you've been the primary reviewer 🙏
> > I look forward to you joining the team!! 🎉
> 
> Thank you @afrittoli , I also referred to previous PRs adding reviewers for the pipeline repo and I found the core collaborators to be the place:) Thank you for clarifying the process and the ladder.

Yes, it looks like we've not been 100% consistent with the documented process in the past, sorry about this.

> And for my reviews:
> 
> * my reviews
>   https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+reviewed-by%3AJeromeJu+-author%3AJeromeju
> * for the primary reviews from my perspective
>   https://docs.google.com/spreadsheets/d/1XsHLcoOnIaASX4UsySf4jRwzB_3LtcD5sFWK6Tunr-8/edit#gid=0

Thanks for sharing this and for your reviews!

/approve

**Review by pritidesai — APPROVED** [review]

**Pull request merged**
