### PR TITLE
Add mpeddada1 from Jib to tektoncd org

### PR DESCRIPTION
**Pull request by mpeddada1**
@chanseokoh

### CODE REVIEW

**Comment by chanseokoh** [comment]
I "/approve." @mpeddada1 is a new Jib team member. The team owns the jib-maven and jib-gradle catalogs. Also see https://github.com/tektoncd/catalog/pull/687

**Comment by chanseokoh** [comment]
I see the "tide" checking is pending. Who can add the "lgtm" label?

**Comment by sbwsg** [comment]
pinging @tektoncd/community-collaborators for an additional set of 👀

**Pull request merged**
