### PR TITLE
Add jagathprakash to tekton members.

### PR DESCRIPTION
**Pull request by jagathprakash**
I am a new joinee to the Google Tekton team.

### CODE REVIEW

**Comment by dibyom** [comment]
Welcome!!
/approve

**Comment by afrittoli** [comment]
Welcome @jagathprakash!

Requirements for joining the Tekton org are document in https://github.com/tektoncd/community/blob/main/process.md#organization-member

Just confirming if you have 2FA enabled in your GitHub account, before this is approved?
Thank you!

**Comment by jagathprakash** [comment]
> Welcome @jagathprakash!
> 
> Requirements for joining the Tekton org are document in https://github.com/tektoncd/community/blob/main/process.md#organization-member
> 
> Just confirming if you have 2FA enabled in your GitHub account, before this is approved? Thank you!

@afrittoli Thanks for looking into this PR. 
I have enabled 2FA for my github account. PFA a pdf file which shows that it has been enabled.
[github-2fa.pdf](https://github.com/tektoncd/community/files/9103428/github-2fa.pdf)

Thanks,
Prakash.

**Review by lbernick — APPROVED** [review]

**Comment by lbernick** [comment]
/lgtm

since dibyo already approved. Doesn't look like we have any specific requirements in our contributor ladder about who/how org membership PRs can be approved, and Prakash has shown that he's enabled 2FA.

**Pull request merged**
