### PR TITLE
Update Roadmap section.

### PR DESCRIPTION
**Pull request by bendory**
Add proposal around a Project-based roadmap.

This is the first step in addressing https://github.com/tektoncd/community/issues/814

This PR is now `Ready to Review`; proposed review process:

- [x] Iterate on [Proposed Query](https://github.com/search?o=desc&q=org%3Atektoncd+type%3Aissue+state%3Aopen+label%3Akind%2Ffeature%2Ckind%2Fbug%2Ckind%2Ftep%2Ckind%2Fproblem+-label%3Alifecycle%2Ffrozen%2Clifecycle%2Fstale%2Clifecycle%2Frotten&s=updated&type=Issues) to populate the project
- [x] Set up the project for consideration with this PR
- [x] Update files in this PR to link to Project

### CODE REVIEW

**Comment by bendory** [comment]
Sample query that we intend to use to populate the project:

https://github.com/search?o=desc&q=org%3Atektoncd+type%3Aissue+state%3Aopen+label%3Akind%2Ffeature%2Ckind%2Fbug%2Ckind%2Ftep%2Ckind%2Fproblem+-label%3Alifecycle%2Ffrozen%2Clifecycle%2Fstale%2Clifecycle%2Frotten&s=updated&type=Issues

**Comment by dibyom** [comment]
PR looks good! For the sample query - are we including or excluding frozen issues (we should include them - we freeze issues as a marker that we want to get to them eventually)

**Review by afrittoli — COMMENTED** [review]
/approve

**Review by vdemeester — APPROVED** [review]

**Comment by bendory** [comment]
I've added a link to the Roadmap Project that we set up.

**Pull request merged**
