### PR TITLE
Add sbwsg as owner on community repo

### PR DESCRIPTION
**Pull request by sbwsg**
I'm an owner on the pipelines repo and would like to help out with approvals
on TEPs related to pipelines.

I've contributed a bit to the community repo already with various TEPs and
process-related changes:

- Step & Sidecar Workspaces TEP: https://github.com/tektoncd/community/pull/225
- Optional Workspaces TEP: https://github.com/tektoncd/community/pull/169
- TEP Template updates: https://github.com/tektoncd/community/pull/268, https://github.com/tektoncd/community/pull/270, https://github.com/tektoncd/community/pull/238

### CODE REVIEW

**Comment by pritidesai** [comment]
@sbwsg I highly appreciate all your efforts and at the same time learn from them 🙏 

/lgtm

**Comment by afrittoli** [comment]
Thank you @sbwsg - that's a big LGTM from me :)
Let's get some more votes from @bobcatfish @ImJasonH @vdemeester @abayer :)

**Review by vdemeester — APPROVED** [review]
/meow
/hold
(to allow other to chim in 😛 )

**Comment by bobcatfish** [comment]
💯 

/lgtm

**Pull request merged**
